query getMediaById(
  $mediaId: Int!
  $scoreFormat: ScoreFormat = POINT_100
) {
  Media(id: $mediaId) {
    id
    title {
      romaji
      english
      native
      userPreferred
    }

    description
    format
    status
    season
    seasonYear
    episodes
    duration
    siteUrl
    bannerImage

    coverImage {
      medium
      large
      extraLarge
      color
    }

    nextAiringEpisode {
      airingAt
      episode
    }

    averageScore
    meanScore
    favourites
    isFavourite
    genres

    mediaListEntry {
			status
      score(format: $scoreFormat)
      repeat
      progress
      updatedAt
      startedAt {
        year
        month
        day
      }
      completedAt {
        year
        month
        day
      }
    }
  }
}
