query userStatistics($userId: Int!) {
  User(id: $userId) {
		id
    statistics {
      anime {
        count
        meanScore
        minutesWatched
        episodesWatched
        scores {
          score
          count
          meanScore
          minutesWatched
        }
        genres {
          genre
          count
          meanScore
          minutesWatched
          mediaIds
        }
				tags {
          count
          meanScore
          minutesWatched
          tag {
            name
            category
            description
            rank
            isAdult
            isGeneralSpoiler
            isMediaSpoiler
          }
					mediaIds
        }
				formats {
          format
          count
          meanScore
          minutesWatched
          mediaIds
        }
				statuses {
          status
          count
          meanScore
          minutesWatched
        }
        countries {
          country
          count
          meanScore
          minutesWatched
          mediaIds
        }
				lengths {
          length
          count
          meanScore
          minutesWatched
          mediaIds
        }
				startYears {
          startYear
          count
          meanScore
          minutesWatched
          mediaIds
        }
				releaseYears {
          releaseYear
          count
          meanScore
          minutesWatched
          mediaIds
        }
				studios {
          studio {
            id
            name
            isAnimationStudio
            isFavourite
            favourites
          }
          count
          meanScore
          minutesWatched
          mediaIds
        }
      }
    }
  }
}
