query statisticsQuery($userId: Int!, $limit: Int) {
  User(id: $userId) {
		id
    statistics {
      anime {
        meanScore
        minutesWatched
        episodesWatched
        count
        statuses {
          status
          meanScore
          minutesWatched
          count
        }
        scores {
          score
          meanScore
          minutesWatched
          count
        }
				startYears {
          startYear
          meanScore
          minutesWatched
          count
        }
        genres(limit: $limit, sort: [COUNT_DESC]) {
          genre
          meanScore
          minutesWatched
          count
          mediaIds
        }
				tags(limit: $limit, sort: [COUNT_DESC]) {
          count
          meanScore
          mediaIds
          minutesWatched
          tag {
            category
            description
            isAdult
            isGeneralSpoiler
            isMediaSpoiler
            name
            rank
          }
        }
      }
    }
  }
}
